export const FUNCTIONS_AND_LIMIT = 'FUNCTIONS_AND_LIMIT';
export const DERIVATIVES_OF_FUNCTIONS = 'DERIVATIVES_OF_FUNCTIONS';
export const USE_OF_DERIVATIVES = 'USE_OF_DERIVATIVES';
export const THE_INTEGRALS = 'THE_INTEGRALS';
export const DESMOS_GRAPH = 'DESMOS_GRAPH';
export const HOME = 'HOME';
